---
abstract: 'Calculate geographic distances.'
author:
  - 'Aran Clary Deltac <bluefeet@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GIS-Distance
no_index:
  directory:
    - inc
    - t
recommends:
  GIS::Distance::Fast: 0.04
  Geo::Ellipsoid: 0.902
requires:
  Class::Measure: 0
  Math::Complex: 0
  Moose: 0.39
  perl: 5.8.3
resources:
  homepage: http://github.com/bluefeet/gis-distance/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bluefeet/gis-distance.git
version: 0.06
